# Generated by Django 2.0.6 on 2018-06-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=450)),
                ('fecha', models.DateTimeField()),
                ('apto', models.CharField(blank=True, choices=[('T', 'Apta para todo público'), ('7', 'Recomendada para mayores de 7 años'), ('12', 'Recomendada para mayores de 12 años'), ('15', 'Apta para mayores de 15 años'), ('18', 'Apta para mayores de 18 años'), ('X', 'Apta para mayores de 18 años, con alto contenido sexual')], default='T', help_text='Identificador de las edades admitidas de acuerdo a la tematica del Evento', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ticket', models.IntegerField()),
            ],
        ),
    ]
