# Generated by Django 2.0.6 on 2018-06-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=450)),
                ('fecha', models.DateTimeField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('apto', models.CharField(blank=True, choices=[('T', 'Apto para todo público'), ('7', 'Recomendada para mayores de 7 años'), ('12', 'Recomendada para mayores de 12 años'), ('15', 'Apto para mayores de 15 años'), ('18', 'Apto para mayores de 18 años'), ('X', 'Apto para mayores de 18 años, con alto contenido sexual')], default='T', help_text='Identificador de las edades admitidas de acuerdo a la tematica del Evento', max_length=2)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento')),
            ],
            options={
                'ordering': ['id_ticket'],
            },
        ),
    ]
