# Generated by Django 2.0.6 on 2018-06-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id_evento',
            field=models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
