# Generated by Django 2.0.6 on 2018-06-21 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20180620_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id_evento',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id_ticket',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
