# Generated by Django 2.0.6 on 2018-06-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20180620_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='id_evento',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
