# Generated by Django 2.0.6 on 2018-06-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20180620_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id_evento',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
