# Generated by Django 2.0.6 on 2018-06-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20180620_1946'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
