# Generated by Django 2.0.6 on 2018-06-21 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(blank=True, max_length=60, null=True)),
                ('tipo_id', models.CharField(blank=True, choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extrangería'), ('PS', 'Pasaporte')], default='T', help_text='Identificador del tipo de identificación', max_length=2)),
            ],
        ),
    ]
