# Generated by Django 2.0.6 on 2018-07-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20180703_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/usuarios'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_id',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extrangería'), ('PS', 'Pasaporte')], default='CC', help_text='Identificador del tipo de identificación', max_length=2),
        ),
    ]
