# Generated by Django 2.0.6 on 2018-06-27 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='slug',
        ),
    ]
