# Generated by Django 2.0.6 on 2018-07-13 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20180712_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'base_manager_name': 'Usuario', 'ordering': ['username']},
        ),
    ]
