# Generated by Django 2.0.6 on 2018-07-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20180705_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(help_text='Número identificación', max_length=20),
        ),
    ]
