# Generated by Django 2.0.6 on 2018-07-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20180712_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['username']},
        ),
    ]
