# Generated by Django 2.0.6 on 2018-06-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='formato dd/mm/YYYY ', null=True),
        ),
    ]
