# Generated by Django 2.0.6 on 2018-07-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20180705_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(upload_to='usuarios'),
        ),
    ]
