# Generated by Django 2.0.6 on 2018-07-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20180705_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='usuarios/img/profile/default_profile.png', upload_to='usuarios/img/profile'),
        ),
    ]
