# Generated by Django 2.0.6 on 2018-06-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20180625_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Correo para registrar su cuenta en Loinkage', max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Formato dd/mm/YYYY ', null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(default=1, help_text='Número identificación', max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/profile'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(help_text='Nombre unico que te identifica en Linkage', max_length=45, unique=True),
        ),
    ]
