# Generated by Django 2.0.6 on 2018-06-26 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20180625_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(help_text='Correo para registrar su cuenta en Linkage', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(default=1, help_text='Número identificación', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(help_text='Nombre único que te identifica en Linkage', max_length=45, unique=True),
        ),
    ]
