# Generated by Django 2.0.6 on 2018-07-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20180708_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='permiso',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
