# Generated by Django 2.0.6 on 2018-07-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20180709_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='descripcion',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='rol',
            name='descripcion',
            field=models.TextField(max_length=400),
        ),
    ]
