# Generated by Django 2.0.6 on 2018-07-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20180709_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['id_permiso', 'permiso'], 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'ordering': ['id_rol', 'rol'], 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['identificacion'], 'verbose_name_plural': 'Usuarios'},
        ),
    ]
