# Generated by Django 2.0.6 on 2019-01-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(help_text='Nombre la categoría', max_length=60, unique=True)),
                ('descripcion', models.CharField(help_text='Descripción de la categoría', max_length=400)),
            ],
            options={
                'verbose_name': 'Categoria',
                'ordering': ['id_categoria'],
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False, verbose_name='Id_lugar')),
                ('slug', models.SlugField()),
                ('nombre', models.CharField(help_text='Nombre del Lugar', max_length=60, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del Lugar', max_length=400, null=True)),
                ('capacidad', models.IntegerField(help_text='Número de personas que caben en el Lugar')),
                ('direccion', models.CharField(blank=True, help_text='Dirección del Lugar', max_length=150, null=True)),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad donde se encuentra el Lugar', max_length=60, null=True)),
                ('img_ppal', models.ImageField(blank=True, default='lugares/img/lugar/default_lugar_ppal.png', help_text='Imagen principal del Lugar', null=True, upload_to='lugares/img/lugar')),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'ordering': ['id_lugar', 'nombre'],
            },
        ),
    ]
