# Generated by Django 2.0.6 on 2018-06-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False, verbose_name='Id_lugar')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=400)),
                ('capacidad', models.IntegerField()),
                ('direccion', models.CharField(max_length=150)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='')),
                ('imagen5', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
