# Generated by Django 2.0.6 on 2018-07-09 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_auto_20180708_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(help_text='Nombre la categoría', max_length=60)),
                ('descripcion', models.CharField(help_text='Descripción de la categoría', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id_lugar', models.AutoField(primary_key=True, serialize=False, verbose_name='Id_lugar')),
                ('name', models.CharField(help_text='Nombre del Lugar', max_length=60, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción del Lugar', max_length=400, null=True)),
                ('capacity', models.IntegerField(help_text='Número de personas que caben en el Lugar')),
                ('addres', models.CharField(blank=True, help_text='Dirección del Lugar', max_length=150, null=True)),
                ('city', models.CharField(blank=True, help_text='Ciudad donde se encuentra el Lugar', max_length=60, null=True)),
                ('img_ppal', models.ImageField(blank=True, default='lugares/img/lugares/default_lugar_ppal.png', help_text='Imagen principal del Lugar', null=True, upload_to='lugares/img/lugares')),
                ('img_slide', models.ImageField(blank=True, help_text='Imagen de un tamaño 1000 x 330 px, para mostrar en el slide de la sección Lugares', null=True, upload_to='lugares/img/lugares')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='lugares/img/lugares')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='lugares/img/lugares')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='lugares/img/lugares')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario')),
                ('category', models.ManyToManyField(to='lugares.Categoria', verbose_name='Lista of categorias')),
            ],
        ),
    ]
