# Generated by Django 2.0.6 on 2018-06-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='administrador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
            preserve_default=False,
        ),
    ]
