# Generated by Django 2.0.6 on 2018-07-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(help_text='Nombre la categoría', max_length=60, unique=True),
        ),
    ]
