# Generated by Django 2.0.6 on 2019-01-15 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('lugares', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lugar',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='lugares.Categoria', verbose_name='Lista of categorias'),
        ),
        migrations.AddField(
            model_name='lugar',
            name='imagenes',
            field=models.ManyToManyField(blank=True, null=True, to='main.Imagen', verbose_name='Lista de imagenes'),
        ),
    ]
