# Generated by Django 2.0.6 on 2018-08-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, to='lugares.Categoria', verbose_name='Lista of categorias'),
        ),
    ]
