# Generated by Django 2.0.6 on 2018-06-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_auto_20180620_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='id_lugar',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
