# Generated by Django 2.0.6 on 2018-07-09 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_auto_20180708_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='lugar',
            options={'verbose_name': 'Lugar'},
        ),
    ]
