# Generated by Django 2.0.6 on 2018-07-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_lugar_administrador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lugar',
            old_name='direccion',
            new_name='addres',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='administrador',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='capacidad',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='imagen1',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='imagen4',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='imagen5',
        ),
        migrations.AddField(
            model_name='lugar',
            name='city',
            field=models.CharField(default='Rionegro', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugar',
            name='description',
            field=models.TextField(default='description', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugar',
            name='img_1',
            field=models.ImageField(default='img', upload_to='lugares/img/lugares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugar',
            name='img_2',
            field=models.ImageField(default='img2', upload_to='lugares/img/lugares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugar',
            name='img_3',
            field=models.ImageField(default='img3', upload_to='lugares/img/lugares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugar',
            name='img_ppal',
            field=models.ImageField(default='imgppal', upload_to='lugares/img/lugares'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lugar',
            name='img_slide',
            field=models.ImageField(default='imgsld', upload_to='lugares/img/lugares'),
            preserve_default=False,
        ),
    ]
