# Generated by Django 2.0.6 on 2018-07-04 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0003_auto_20180703_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='addres',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Usuario'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to='lugares/img/lugares'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='lugares/img/lugares'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to='lugares/img/lugares'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='img_slide',
            field=models.ImageField(blank=True, null=True, upload_to='lugares/img/lugares'),
        ),
    ]
