# Generated by Django 2.0.6 on 2018-06-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0003_auto_20180620_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='id_lugar',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id_lugar'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Nombre'),
        ),
    ]
