# Generated by Django 2.0.6 on 2018-07-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0003_auto_20180709_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lugar',
            options={'ordering': ['id_lugar', 'nombre'], 'verbose_name': 'Lugar', 'verbose_name_plural': 'Lugares'},
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='capacity',
            new_name='capacidad',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='category',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='city',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='addres',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='name',
            new_name='nombre',
        ),
    ]
