# Generated by Django 2.0.6 on 2018-07-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0004_auto_20180703_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='addres',
            field=models.CharField(blank=True, help_text='Dirección del Lugar', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='capacity',
            field=models.IntegerField(help_text='Número de personas que caben en el Lugar'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='city',
            field=models.CharField(blank=True, help_text='Ciudad donde se encuentra el Lugar', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del Lugar', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='img_ppal',
            field=models.ImageField(help_text='Imagen principal del Lugar', upload_to='lugares/img/lugares'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='img_slide',
            field=models.ImageField(blank=True, help_text='Imagen de un tamaño 1000 x 330 px, para mostrar en el slide de la sección Lugares', null=True, upload_to='lugares/img/lugares'),
        ),
        migrations.AlterField(
            model_name='lugar',
            name='name',
            field=models.CharField(help_text='Nombre del Lugar', max_length=60, verbose_name='Nombre'),
        ),
    ]
