# Generated by Django 2.0.6 on 2018-07-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0005_auto_20180704_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugar',
            name='img_ppal',
            field=models.ImageField(blank=True, help_text='Imagen principal del Lugar', null=True, upload_to='lugares/img/lugares'),
        ),
    ]
